### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by SMD-7** [SMD-7/Catch_it#2]

**Comment by ashiscs** [comment]
@SMD-7 sir can you tell me what do I need to update in the README file?

**Comment by SMD-7** [comment]
Okay so @ashiscs provide them the contribution, githelp link for there help and this repository will contain stuff related to all the tech present out there in the market....

**Comment by ashiscs** [comment]
> Okay so @ashiscs provide them the contribution, githelp link for there help and this repository will contain stuff related to all the tech present out there in the market....

Okay got it sir, will create a one!
